trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerRegistryServiceConnection: 'your-acr-service-connection'
  imageRepository: 'your-image-name'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
  azureSubscription: 'your-azure-subscription'
  appName: 'your-app-service-name'
  acrName: 'your-acr-name'

stages:
- stage: Build
  displayName: Build and Push Docker Image
  jobs:
  - job: BuildAndPush
    displayName: Build and Push
    steps:
    - task: Docker@2
      displayName: Build and push an image to Azure Container Registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

- stage: Deploy
  displayName: Deploy to Azure App Service
  jobs:
  - job: DeployApp
    displayName: Deploy App
    steps:
    - task: AzureWebAppContainer@1
      displayName: Deploy Azure Web App Container
      inputs:
        azureSubscription: $(azureSubscription)
        appName: $(appName)
        imageName: '$(acrName).azurecr.io/$(imageRepository):$(tag)'